### ISSUE TITLE
有mac版本的软件吗

### ISSUE THREAD

**Issue by cddehsy** [Qalculate/libqalculate#295] opened 2021-06-03 13:49 UTC

**Comment by hanna-kn** [comment] 2021-06-03 14:00
https://ports.macports.org/?search=qalculate&search_by=name
https://formulae.brew.sh/formula/libqalculate

Duplicate of https://github.com/Qalculate/qalculate-gtk/issues/254

**Closed by hanna-kn** 2021-06-03 14:00 UTC
