### ISSUE TITLE
Cannot define a function with unit conversion

### ISSUE THREAD

**Issue by agguser** [Qalculate/libqalculate#557] opened 2023-07-16 19:54 UTC
```ini
$ qalc
> 2 in to cm
  2 inches = 5.08 cm

> f() := \x in to cm
  save(x inches, f()) = \x in   # note that no 'to cm' 
> f 2
  f(2) = 2 in   # expect '5.08 cm'

> f() := (\x in to cm)
  …   # same

> f() := \x in cm
  save(x inch·centimeters, f()) = \x in*((1/100) m)   # OK, but result unit is not cm
> f 2
  f(2) = 508 mm²   # expect '5.08 cm'
```

**Comment by hanna-kn** [comment] 2023-07-17 05:01
"to" is not supported in function expression (primarily because this would not change the actual value of the function result, and any units might nevertheless change again before presented to the user).

`to cm` is always removed from the expression (regardless of parentheses) before calculation, e.g. `f() := \x in to cm` is interpreted as `save(x inches, f())`, and the result of this expression is then converted to cm (which is not meaningful).

The command `function f \x in to cm` won't work as intended either, even though `to cm` will actually be included in the function expression (in this case `to` will be interpreted as `ton × \o`).

I would recommend that you use division instead, e.g. `f()=x in/cm` or `f()=(x in/cm) cm`, although in the latter example neither prefix nor unit might be preserved depending on settings and how the function is used.

**Closed** 2023-07-17 09:56 UTC
