### ISSUE TITLE
invalid timestamp eurofxref-daily.xml

### ISSUE THREAD

**Issue by Konfekt** [Qalculate/libqalculate#215] opened 2020-08-05 05:58 UTC
The time stamp of the file   .local/share/qalculate/eurofxref-daily.xml is invalid;
in the file manager the year 2100 is shown.
Rsync complains that
```
  Time value of .local/share/qalculate/eurofxref-daily.xml truncated on receiver.
```
This happens with libqualculate14 2.2.1-lp152.4.10 on openSUSE 15.2 (but also occurred before in 15.1).

**Comment by hanna-kn** [comment] 2020-08-06 04:22
This has been fixed in later versions of libqalculate (>= 2.6.0).

It was caused by an uninitialized variable and is fixed by the following patch:
```
--- a/libqalculate/Calculator.cc	2018-01-17 09:47:51.000000000 +0100
+++ b/libqalculate/Calculator.cc	2020-08-06 06:19:52.778921785 +0200
@@ -9521,7 +9521,7 @@
 	char error_buffer[CURL_ERROR_SIZE];
 	CURL *curl;
 	CURLcode res;
-	long int file_time;
+	long int file_time = 0;
 	curl_global_init(CURL_GLOBAL_DEFAULT);
 	curl = curl_easy_init();
 	if(!curl) {return false;}
```

**Closed by hanna-kn** 2020-08-06 04:22 UTC
