### ISSUE TITLE
Ukraine flag

### ISSUE THREAD

**Issue by galileo-pkm** [Qalculate/libqalculate#434] opened 2022-04-23 03:33 UTC
What do I see a Ukranian flag when I start Qalculate?
If this is some virtue signalling by the authors ask yourself how come you
felt no need to do the same with Yemen where an order of magnitude more people
have died including 85000 children under the age of 5. 

![image](https://user-images.githubusercontent.com/8114900/164873422-c0830ef9-4c45-42e7-aa94-2e9afb4b0bfb.png)

**Comment by hanna-kn** [comment] 2022-04-23 06:26
Duplicate of https://github.com/Qalculate/qalculate-gtk/issues/389

I'm sorry if you are somehow offended (I really hope that you haven't been duped by Putin's ridiculous lies, or by the usual "alternative facts" from the far-right) by such a minuscule statement, which disappears when the application is restarted. 

I'm also sorry that I haven't publicly protested against the atrocities in Yemen.

The "Queer calculator" (and its author) has never made claims about being apolitical.

Please update to the latest version (4.1.1).

**Closed by hanna-kn** 2022-04-23 06:26 UTC

**Comment by galileo-pkm** [comment] 2022-06-20 02:55
I failed to realize that Jacobin magazine or journalist like Aaron Mate, Max Blumenthal, Eva Bartlett, Benjamin Norton, Yasha Levine and many others are far right. 
Hopefully by now you have figured out how your media lied to you.

**Comment by hanna-kn** [comment] 2022-06-20 03:36
@galileo-pkm 
Regrettably there are a small minority of dictator apologists also on the left.
