### ISSUE TITLE
"day hr" parsing has changed

### ISSUE THREAD

**Issue by SubhashBose** [Qalculate/libqalculate#482] opened 2022-10-24 01:40 UTC
Previously (at least in v4.1.1) parsing was like this
`7day 5hr = (7 × day) + (5 × hour)`

but now parsing is happing like this
`7day 5hr = 7 days × 5 hours`

Is this an intentional change? But I kind of preferred the older parsing method.

**Comment by hanna-kn** [comment] 2022-10-24 06:38
This has not changed. Perhaps you've changed parsing mode to "conventional"?

**Comment by SubhashBose** [comment] 2022-10-24 07:22
Ok. Sorry for the confusion. Parsing mode is fine, it is set to adaptive.

Now I see what has happened. I edited the 'hour' unit to accept 'h, hrs' 
this is the entry of names from my units.xml
`<names>ar:h,hour,p:hours,a-cr:hr,p:hrs</names>`
As a result, now none of the names are accepted in adaptive parsing. After clearing the changes from unit.xml, now the adaptive parsing is working.

So, I guess users are not supposed to edit the units like hours, inches etc. for adaptive parsing to work?
If so, can you add 'hr', 'hrs' names to 'hour' unit?

Also, I think there is bug in latest version of  Qalqualte-gtk. When I go to edit names for units, I can no longer see any names there. This is true for all units.
![image](https://user-images.githubusercontent.com/22131647/197469348-ddbbcf60-8fd2-461d-ab43-b107e78192c5.png)

**Comment by hanna-kn** [comment] 2022-10-24 07:58
> Parsing mode is fine, it is set to adaptive.

It should also work with "implicit first". It only works if implied multiplication (without multiplication sign) is used, but "conventional" does not differ between implicit and explicit multiplication.

> So, I guess users are not supposed to edit the units like hours, inches etc. for adaptive parsing to work?

The issue is that the original unit is not replaced but deactivated, and the day unit is refers to the original hour unit. It should work if also edit the day unit.

> If so, can you add 'hr', 'hrs' names to 'hour' unit?

Done.

> Also, I think there is bug in latest version of Qalqualte-gtk. When I go to edit names for units, I can no longer see any names there. This is true for all units.

Now fixed.

**Comment by SubhashBose** [comment] 2022-10-24 10:17
Thanks. It seem to be working.

But I see a strange issue. Sometimes "7d 5h" is parsed as multiplication, although the result shows addition. But if I again simply  repeat the same expression, then it parses correctly
![image](https://user-images.githubusercontent.com/22131647/197502760-5df522e2-b4a9-4abd-95ff-92c1dc4a6731.png)

This I checked only in the qalc command line interface. Just to be sure my units.xml has no entry related to hours or any time base units.

**Comment by SubhashBose** [comment] 2022-10-24 10:35
Ok. It's not random. On a fresh session, this will not occur. If you run any other expressions first, then run this one, this parsing error will occur, but on repeating the same expression again parsing error will not be there.

![image](https://user-images.githubusercontent.com/22131647/197507016-536c460a-ae95-4a5e-8fcf-f5047f7ba4b0.png)

**Comment by hanna-kn** [comment] 2022-10-24 12:47
> But I see a strange issue. Sometimes "7d 5h" is parsed as multiplication, although the result shows addition. But if I again simply repeat the same expression, then it parses correctly

Fixed (in parentheses property was not cleared after previous expression).

> On a fresh session, this will not occur. If you run any other expressions first, then run this one, this parsing error will occur, but on repeating the same expression again parsing error will not be there.

It requires that the whole previous expression is in parentheses or that the expression consists of a single function.

**Closed** 2022-11-14 08:39 UTC
