### ISSUE TITLE
64-bit Windows installer failure, and truncation (instead of round to nearest) of result

### ISSUE THREAD

**Issue by PowerUser1234** [Qalculate/libqalculate#329] opened 2021-09-09 12:19 UTC
-The Win64 offline installer from the website won't install the program in 64 bit Windows 10.
Can someone tell me what I need to do to get a 64 bit Win installer that works?

-Is there an offline installer that will run on the 64 bit Linux command line, on its own?
If so, where on the free public internet can I obtain it?

**Comment by abrac** [comment] 2021-09-09 17:09
This webpage is for the Qalculate command line program. If you are looking for Qalculate with a graphical interface, you should download it [here](https://github.com/Qalculate/qalculate-gtk/releases).

If you are indeed trying to get the command line program:

1. Are you sure you downloaded the installer from this website? Download it from the [releases page](https://github.com/Qalculate/libqalculate/releases). If that is where you downloaded previously, what error did you get?

2. You should download the linux binary from the [releases page](https://github.com/Qalculate/libqalculate/releases) above. It is the file with the `tar.gz` extension. Which Linux distribution are you using?

**Comment by PowerUser1234** [comment] 2021-09-10 01:06
The following is the series of Windows and notifications that appears when I tried to double click
and installed the 64 bit Qalculate! installer from the link above to the releases page.

**Windows protected your PC
more info
Run anyway
The advertised appllication will not be installed because it might be unsafe.
Contact your administrator to change the installation user interface option
of the package to basic.
Installation Incomplete
The installer was interrupted becofre Qalculate! could be installed.  You need
to restar the installer to try again.  Click "Close" to exit.
Close**

Is there something simple I can do?  Or do you guys need to alter the installation program at your end?

**Comment by abrac** [comment] 2021-09-10 04:42
So it gives that error when you press "Run Anyway"? I think the simplest thing to do is to just disable *Windows SmartScreen* in Settings.

**Comment by hanna-kn** [comment] 2021-09-10 07:24
> Can someone tell me what I need to do to get a 64 bit Win installer that works?

If for some reason you are not allowed to, or do not want to, install external applications like Qalculate in Windows, I suggest that you try the [32-bit "portable" zip package](https://github.com/Qalculate/qalculate-gtk/releases/download/v3.20.1/qalculate-3.20.1-i386.zip) which does not require installation.

> -Is there an offline installer that will run on the 64 bit Linux command line, on its own?

The "self-contained" binaries ([qalculate-3.20.1a-x86_64.tar.xz](https://github.com/Qalculate/qalculate-gtk/releases/download/v3.20.1/qalculate-3.20.1a-x86_64.tar.xz)) does not even require installation.

**Comment by PowerUser1234** [comment] 2021-09-10 07:36
-I am not using Microsoft Edge for my Internet.  I am using 64 bit Firefox version 92.0.

-Is there a self contained binaries package for Win64 Qalculate?  When will I be able to use 
Win64 Qalculate?

**Comment by hanna-kn** [comment] 2021-09-10 09:28
> Is there a self contained binaries package for Win64 Qalculate? When will I be able to use
Win64 Qalculate?

The 32-bit version should work without issues in 64-bit Windows. There shouldn't be any discernible differences compared to 64-bit binaries.

> I cannot work out what M+ (Memory Plus) is in 32 bit Qalculate, and how to use it, in terms of MR (Memory Recall). Can someone please reply here explaining these?

M+ adds the current value to contents of the memory buffer, while MR returns the value of the memory buffer. MR is in Qalculate implemented as variable, which means that you can type use MR in any expression (e.g. `sin MR`), but it also currently means that you have to click = or press Enter to display the the value of the memory after clicking on the MR button (I might change this).

E.g. if you click 5, M+, 3, M+, MR, and =, the result will be 8.

> When using command line Qualculate, what do I type to alter the precision of values calculated in "normal" mode? Is there a configuration file where this instruction can be stored, so that the Qalculate command line program can be preconfigured

Use `set prec` (or `set precision`, eg `set precision 20`), in interactive mode (when started without any expression), or the --set/-s command line switch with the same option (e.g. `qalc -s "prec 20"`).

**Comment by PowerUser1234** [comment] 2021-09-11 02:04
Dear Qalculate,

Use set prec (or set precision, eg set precision 20), in interactive mode (when started without any expression), or the --set/-s command line switch with the same option (e.g. qalc -s "prec 20").

-Is there a configuration file where this instruction can be stored, so that the Qalculate command line program can be preconfigured
for every time that it runs, or is called?

The 32-bit version should work without issues in 64-bit Windows. There shouldn't be any discernible differences compared to 64-bit binaries.

-When will there be the option to have a working Win64 or Linx64 version of the software?  I have real cause to be running
the software in 64 bit.

?

Z.M.
________________________________

**Comment by hanna-kn** [comment] 2021-09-11 06:47
> Is there a configuration file where this instruction can be stored, so that the Qalculate command line program can be preconfigured for every time that it runs, or is called?

If you use the command in "interactive" mode, the setting will be saved on exit. The settings can be changed in the qalc.cfg in ~/.config/qalculate on GNU/Linux, or in AppData/Local/Qalculate, or the _user_ directory if the "portable" zip version is used, on Windows.

> I have gone 2,M+,3,M+,5,M+,MR,=, the answer given should be 10, but it isn't, I am getting a different answer each time.  What it is telling me is 28.  I think I have discovered a bug here, that should be repaired.

Did you clear the memory (MC) each time (or use memory store, MS, instead of M+ for the first click)? The memory buffer functionality is primarily useful for users accustomed to it from traditional calculators. I personally prefer to use ANS, variables, or to click on paste icon of the relevant result.

> When will there be the option to have a working Win64 or Linx64 version of the software?  I have real cause to be running
the software in 64 bit?

All official GNU/Linux versions binaries are 64-bit. Why do you require that the binaries are 64-bit? (I provide installers for both 64-bit and 32-bit binaries for Windows, bit I've decided to avoid unnecessary work by only providing a single 32-bit version of the version that do not require installation.)

**Comment by abrac** [comment] 2021-09-11 06:53
> I have gone 2,M+,3,M+,5,M+,MR,=, the answer given should be 10

Make sure you clear your memory first, with MC.

**Comment by PowerUser1234** [comment] 2021-09-12 10:45
-What progress is going to be being made on the Win64 version of Qalculate?  Particularly on the website's offline
installer, which halts too early and will not install the software?

**Comment by hanna-kn** [comment] 2021-09-12 17:11
> What progress is going to be being made on the Win64 version of Qalculate? Particularly on the website's offline
installer, which halts too early and will not install the software?

The offline installer halts because the settings of your system does not allow installation of unverified software. This will likely not change. The "portable" zip version is however functionally identical. You are also welcome to try installing Qalculate using the Windows package manager, winget (https://docs.microsoft.com/en-us/windows/package-manager/winget/).

**Comment by PowerUser1234** [comment] 2021-09-13 01:30
Success!  In the end I had to go to [https://www.microsoft.com/en-us/p/app-installer/9nblggh4nns1#activetab=pivot:overviewtab](https://www.microsoft.com/en-us/p/app-installer/9nblggh4nns1#activetab=pivot:overviewtab) to successfully download and install winget, but that works, in Username.  I have thereby downloaded and installed what does indeed seem to be a working 64 bit version of Qalculate.  Many thanks for the pointer in the right direction.

I have have gone Mode\Precision  and change the value precision to 100.  I have then asked it to decimal evaluate 1/11.
What I find then is that the final decimal place is rounded up, and not truncated.  Where in Qalculate do I go to prevent
rounding of the final decimal place, and to just allow Qalculate to simply truncate the value at that point, and do nothing else?

**Comment by hanna-kn** [comment] 2021-09-13 06:15
> Where in Qalculate do I go to prevent rounding of the final decimal place, and to just allow Qalculate to simply truncate the value at that point, and do nothing else?

I suggest that you try the "Indicate repeating decimals" option (`set repdeci 1` in qalc, Preferences->Number & Operators in the new UI, Mode->Numerical Display in the old UI). This does however only work with rational numbers. Otherwise you'll have to use `trunc(1/11*10^100)/10^100` or similar.

**Comment by PowerUser1234** [comment] 2021-09-13 06:31
-What I can do is just ask for a precision of 1 greater than what I need, which will display the situation, and I can use my own eyes and head, or another API to truncate after that.  Is the specific option to disable this final decimal point rounding behaviour
a candidate for addition to Qalculate?

-I still can't get winget to both download and install the 64 bit version of the software anymore.  The installation worked the first time, however I had an (unlikely) reason to temporarily uninstall Qalculate!.  Now that I want to reinstall Qalculate, winget
crashes after download, with this same error number, and set of notifications.  What do i do to get winget downloading
and installation to work?

**Comment by hanna-kn** [comment] 2021-09-13 17:16
> What I can do is just ask for a precision of 1 greater than what I need, which will display the situation, and I can use my own eyes and head, or another API to truncate after that.

That does not seem to be wise. E.g. 1/2451 rounded to 7 decimals is 0.0004080 and to 8 decimals 0.00040800, but truncated to 7 decimals 0.0004079.

If you use "indicate repeating decimals", 1/11 will return `0.090 90...` and you can append as many "90" as you like (in your head or otherwise).

I might consider adding a second argument, specifying the number of decimals (as in round() function), to the trunc() function. You can however easily add your own function (with expression `trunc(x*10^precision)/10^precision`)

> Is the specific option to disable this final decimal point rounding behaviour a candidate for addition to Qalculate?

To determine this I, need to know in which contexts this would be useful. It would probably not be difficult to implement for rational numbers, but I'm not sure how this should work for irrational numbers (floating point calculations) and values with uncertainty, and the repeating decimals option should generally be more useful.

> I still can't get winget to both download and install the 64 bit version of the software anymore. The installation worked the first time, however I had an (unlikely) reason to temporarily uninstall Qalculate!. Now that I want to reinstall Qalculate, winget
crashes after download, with this same error number, and set of notifications. What do i do to get winget downloading
and installation to work?

I'm no Windows expert and I cannot help you further with this. It would however be helpful if you could tell me the reason why you need the 64-bit version (so I can determine if I should make a 64-bit version of the binaries that do not require installation).

**Comment by PowerUser1234** [comment] 2021-09-14 05:07
-Why do I insist on a Win64 version of the software?  Because I have 64 bit hardware, and I wish to be able to take full advantage of the software, in terms of computation activity and speed, via software logic.  Which might show up with 10,000 or 100,000 significant figures as the result from some mathematical expression.  Given the misbehaviour of the offline Win64 installer, and the misbehaviour of the winget installation process, I now have no access to that version of the Qalculate! software.

-From a mathematical, numerics point of view, a decimal value due to a rational or an irrational number, infinitely recurring, will have to be stopped, and considered no further, at some point.  From that initial point of view, sheer truncation of the decimal value, as specified via precision or decimal settings, is the key.  What you need is placement accuracy of every digit in an integer or decimal placement, whenever it is appropriate to end such.  Rounding final decimal places means that there is object inclarity in innacuracy of some amount (unknown) of final decimal places, and innacuracy by digits (unknown) if there is a rounding scheme in place, by default.  Rounding of decimal places alone become counter productive, since the difference between the rounded value and a digit placement accurate value is unknown.  Unless default decimal rounding is abandoned, or may be disabled by a specific, clear, self explanatory setting which is easy to find, which is another key towards accuracy.  What do you guys think?

**Comment by hanna-kn** [comment] 2021-09-14 11:53
> Why do I insist on a Win64 version of the software? Because I have 64 bit hardware, and I wish to be able to take full advantage of the software, in terms of computation activity and speed, via software logic. Which might show up with 10,000 or 100,000 significant figures as the result from some mathematical expression.

I've now compiled 64-bit binaries that does not require installation:
https://github.com/Qalculate/libqalculate/releases/download/v3.20.1/qalculate-3.20.1-x64.zip

Since you seem very passionate about this, please compare with the 32-bit version and report any performance differences you find.

> Given the misbehaviour of the offline Win64 installer, and the misbehaviour of the winget installation process, I now have no access to that version of the Qalculate! software.

It is my impression that the issue is not caused by any misbehaviour of the Qalculate installer specifically.

> From a mathematical, numerics point of view, a decimal value due to a rational or an irrational number, infinitely recurring, will have to be stopped, and considered no further, at some point. From that initial point of view, sheer truncation of the decimal value, as specified via precision or decimal settings, is the key. What you need is placement accuracy of every digit in an integer or decimal placement, whenever it is appropriate to end such. Rounding final decimal places means that there is object inclarity in innacuracy of some amount (unknown) of final decimal places, and innacuracy by digits (unknown) if there is a rounding scheme in place, by default. Rounding of decimal places alone become counter productive, since the difference between the rounded value and a digit placement accurate value is unknown. Unless default decimal rounding is abandoned, or may be disabled by a specific, clear, self explanatory setting which is easy to find, which is another key towards accuracy. What do you guys think?

I'm not aware of any context where truncation is standard, and I'm not familiar with any software which provides this as an option. In my opinion the "indicate repeating decimals" option (combined with adequate precision; it might be beneficial to add an option to always provide the required number of decimals for recurrence to appear) is a reasonable solution which does confuse the accuracy of the result (the truncated value is never closer the true value than a properly rounded value). For irrational values, I recommend activating "Interval" as interval display mode.

**Comment by PowerUser1234** [comment] 2021-09-15 07:00
-I have followed this advice.  I have then tried to view the store function for pi, from a precision of 100 to 102.
The last digits change from 068 to 06799.  Is there any one settings way to get things to truncate for any 
calculated precision value, could an update or an additional setting be put in to do truncation, with absolutely
no default decimal place rounding that behaves like this?

**Comment by hanna-kn** [comment] 2021-09-15 08:41
> I have then tried to view the store function for pi, from a precision of 100 to 102. The last digits change from 068 to 06799.

I'm not sure what you mean with "view the store function"? If you store the value of calculated (approximated) pi in a variable, it will be saved as an interval (`interval(3.1415926535897932384626433832795028841971693993751058209749445923078164062862089986280348253421170679821480865132823066470938446095, 3.1415926535897932384626433832795028841971693993751058209749445923078164062862089986280348253421170679821480865132823066470938446096)`).

If you change the interval display mode to "interval" the calculated result of pi will be displayed as "intervall(3.141 592 653, 3.141 592 654)". In the new GUI (qalculate-qt), in qalc, and in the configuration file of qalculate-gtk you can select "lower" interval display mode. The value will then be displayed as "3.141 592 653".

I might consider adding more default rounding options (truncation is just another form of rounding). There however a lot of variants, which are more or less useful and results in smaller or greater error depending context (see https://en.wikipedia.org/wiki/Rounding).

**Comment by PowerUser1234** [comment] 2021-09-15 10:44
Dear Qalculate,

It would be really brilliant if you would disable final decimal places rounding.
Your program has a Graphical User Interface, but also a command line
access, so that it can be called from another program, which may communicate
with it.

I would highly recommend this change, and may end up using your program if this happens.

Yours Sincerely,

Z.M.
________________________________

**Comment by PowerUser1234** [comment] 2021-09-21 04:50
_If you change the interval display mode to "interval" the calculated result of pi will be displayed as "intervall(3.141 592 653, 3.141 592 654)". In the new GUI (qalculate-qt), in qalc, and in the configuration file of qalculate-gtk you can select "lower" interval display mode. The value will then be displayed as "3.141 592 653"._

-In the non-GTK GUI version of Qualculate, this still means that I am getting default rounding of a decimal place.
For example, 2/3 gives ~0.6666666667 when Precision=10. How can I get Qualculate to print to screen
answers which never have this default rounding of the right hand side of a decimal, or mixed number decimal,
in this fashion, but would instead, for this example, have just truncated, and done absolutely no more?
It should give me an answer like ~0.6666666666.

-Can someone introduce a change to default decimal evaluation like this, or add in a setting that will hold evaluation
to truncation only, with no decimal place rounding at all?

**Comment by hanna-kn** [comment] 2021-09-21 11:25
> In the non-GTK GUI version of Qualculate, this still means that I am getting default rounding of a decimal place.
For example, 2/3 gives ~0.6666666667 when Precision=10.

2/3 is a rational number (not affected by the interval display mode), thus you'll need to activate "indicate repeating decimals" in this case. If both settings are activated it should cover both rational and irrational numbers.

Alternatively create the suggested function (`trunc(x*10^precision)/10^precision`), assign it to a button, and create a keyboard shortcut.

> Your program has a Graphical User Interface, but also a command line access, so that it can be called from another program, which may communicate with it.

This only makes it more important to reduce potential rounding errors.

**Comment by PowerUser1234** [comment] 2021-09-22 06:37
I have gone both **Mode\Interval Display\Interval** and **Mode\Numerical Display\Indicate Repeating Zeroes**.
This does now, on certain occasions, give me the final decimal place rounded answer and the truncated one,
with interval() around them both.

Is there some way I can affect things from here, so that I don't get this terrible visual display of both values,
but that I get the truncated only value, an approximately equal to sign, and nothing else displayed?

**Comment by hanna-kn** [comment] 2021-09-22 08:14
> Is there some way I can affect things from here, so that I don't get this terrible visual display of both values,
but that I get the truncated only value, an approximately equal to sign, and nothing else displayed?

Change `interval_display=2` to `interval_display=5` in the configuration file (user/qalculate-gtk.cfg).

**Comment by PowerUser1234** [comment] 2021-09-22 09:25
Thanks a heap for this!  It seems that I pretty well have what I am after.   With all three of 
**Mode\Interval Display\Interval**, **Mode\Numerical Display\Indicate Repeating Zeroes** and
**interval_display=5** within **qalculate-gtk.cfg** that I pretty much have what I am after.
I find that if I turn off Indicate Repeating Zeroes, that the old problem of final decimal rounding
is in there, underneath, somehow.  Is there a way for me to avoid my problem with
Display Indicating Zeroes set to off?

**Comment by hanna-kn** [comment] 2021-09-23 13:51
> I find that if I turn off Indicate Repeating Zeroes, that the old problem of final decimal rounding
is in there, underneath, somehow. 

I assume that you mean "Indicate Repeating Decimals" (and not "Show Ending Zeroes").

"Indicate Repeating Zeroes" affects exact rational numbers, which does not have an exact decimal representation, while "Interval Display" affects approximated values (primarily intended for calculations involving values with potential measurement errors). Note also that I would never recommend using "Interval Display" for truncation of digits for important calculations, or in any scientific context.

> Is there a way for me to avoid my problem with Display Indicating Zeroes set to off?

Only if you use the suggested method using the trunc() function.

> I still can't get the 64 bit Windows offlline installer to work, and have to use the .zip code bundled version. Maybe you guys should consider fixing the installation download at some point!

As previously stated, the issue is caused by the restrictive permissions on your system.

> Why isn't the last line justified to the left?

All results are right aligned. It would look odd if multi-line results were aligned differently.

> Can't there be an option to turn the initial Display area into a Vertical Scroll area, so that the long numbers can fit in the initial Display area.

It would still not be very practical. The command line version and, to a certain degree, the new GUI (qalculate-qt), are better suited for very long results (with very high precision).

**Comment by hanna-kn** [comment] 2021-09-23 13:58
> I still can't get the 64 bit Windows offlline installer to work, and have to use the .zip code bundled version. Maybe you guys should consider fixing the installation download at some point!

Have you tried only installing it for a single user, or in an administrative command prompt with /qb switch (`msiexec.exe /i qalculate-3.20.1-x64.msi /qb`)?

**Closed** 2021-12-13 07:44 UTC
